<?php
/**
 * @file
 * Boost Warmer
 * May 2 2013, Kendall Anderson
 *
 * Events that we care about:
 *
 * 1. hook_cron() (Drupal's general cron event)
 *   
 *    This is where we add any additional elements to sitemap.xml if necessary,
 *    and generate the sitemap.dynamic.txt file to provide additional urls
 *    to boost that may not exist in sitemap.xml.
 *
 * 2. boost_warmer_page_crawl()
 *
 *    Loading this page causes pages that aren't currently boosted, to be
 *    requested (thereby warming the boost cache for them).
 *
 *
 *
 * INSTALLATION
 * See installation.txt file.
 */


define('BOOST_WARMER_PATH', 'boost-warmer/crawl');

/**
 * Implements hook_cron().
 */
function boost_warmer_cron() {
  // Ask modules for urls to request that may not be in sitemap.xml.
  $hook     = 'boost_warmer_get_urls';
  $modules  = module_implements($hook);

  $items = array();
  foreach ($modules as $module) {
    $items[] = module_invoke($module, $hook);
  }

  boost_warmer_save_dynamic_urls($items);
}

/**
 * Save the dynamic urls discovered by hook_boost_warmer_get_urls() to a file
 * that can be processed by the crawler.
 */
function boost_warmer_save_dynamic_urls($item_groups) {
  $file = boost_warmer_get_filename();
  if (file_exists($file)) {
    unlink($file);
  }

  if (!count($item_groups)) {
    return;
  }

  // Combine all urls found during hook_boost_warmer_prepare().
  $urls = array();
  foreach ($item_groups as $items) {
    if (count($items)) {
      $urls = array_merge($urls, $items);
    }
  }

  // Preprend all urls with the domain name.
  $path = variable_get('xmlsitemap_base_url', '') . '/';
  for ($i=0; $i<count($urls); $i++) {
    $urls[$i] = $path . $urls[$i];
  }

  file_put_contents($file, implode("\n", $urls));
}



/**
 * Implements hook_menu().
 */
function boost_warmer_menu() {
  $items = array();
  $items[BOOST_WARMER_PATH] = array(
    'type'            => MENU_CALLBACK,
    'page callback'   => 'boost_warmer_page_crawl',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * There are 2 steps to the crawl process:
 * 1. Run boost_cron() to delete any cached html files that have expired.
 * 2. Crawl any pages that haven't been cached yet.
 */
function boost_warmer_page_crawl() {
  // Tell boost to remove any cached html files that have expired.
  boost_cron();

  // Crawl any pages that haven't been cached yet.
  $o = new BoostWarmer();
  $o->crawl();

  // Force a clean exit, with no output.
  return 'test';
  exit(0);
}



/**
 * Return the path/filename to the dynamic sitemap urls list.
 */
function boost_warmer_get_filename() {
  $path = variable_get('file_public_path', 'files') . '/';
  return $path . 'sitemap.dynamic.txt';
}

